### PR TITLE
Add Support for Ollama

### PR DESCRIPTION
**Pull request by jgpruitt**
Adds support for interacting with LLMs running in [Ollama](https://ollama.com/).

### CODE REVIEW

**Review by jonatas — COMMENTED** [review]
I did make install, recreated the docker image and got the following error:
```
postgres=# select ollama_chat_complete
( 'llama3'
, jsonb_build_array
  ( jsonb_build_object('role', 'system', 'content', 'you are a helpful assistant')
  , jsonb_build_object('role', 'user', 'content', 'what is the typical weather like in Alabama in June')
  )
, _options=> jsonb_build_object
  ( 'seed', 42
  , 'temperature', 0.6
  )
) as actual;
WARNING:  defaulting Ollama host to: http://localhost:11434
ERROR:  httpx.ConnectError: [Errno 99] Cannot assign requested address
CONTEXT:  Traceback (most recent call last):
  PL/Python function "ollama_chat_complete", line 36, in <module>
    resp = client.chat(_model, _messages_1, stream=False, **args)
  PL/Python function "ollama_chat_complete", line 179, in chat
```
Same for the other functions, even tried to assign the address.
 
```sql
postgres=# select current_setting('ai.ollama_host');
    current_setting
------------------------
 http://localhost:11434
(1 row)

postgres=# select * from ollama_list_models();
ERROR:  error fetching next item from iterator
DETAIL:  httpx.ConnectError: [Errno 99] Cannot assign requested address
CONTEXT:  Traceback (most recent call last):
  PL/Python function "ollama_list_models", line 332, in <module>
  PL/Python function "ollama_list_models", line 68, in _request
  PL/Python function "ollama_list_models", line 826, in request
  PL/Python function "ollama_list_models", line 913, in send
  PL/Python function "ollama_list_models", line 941, in _send_handling_auth
  PL/Python function "ollama_list_models", line 978, in _send_handling_redirects
  PL/Python function "ollama_list_models", line 1014, in _send_single_request
  PL/Python function "ollama_list_models", line 231, in handle_request
  PL/Python function "ollama_list_models", line 154, in __exit__
  PL/Python function "ollama_list_models", line 85, in map_httpcore_exceptions
PL/Python function "ollama_list_models"
```

**Comment by jgpruitt** [comment]
@jonatas is Ollama running on your host machine and pgai running in docker? If so, you need to use http://host.docker.internal:11434

**Comment by jgpruitt** [comment]
If that fixes it, I guess I should improve the docs with this info

**Review by jonatas — APPROVED** [review]
Very good! everything worked as expected when I fixed it.

We should be clear about the machine people need to get it running in a considerable speed.

<details>
  <summary>In my mac M1 2020 it took `Time: 67653.359 ms (01:07.653)` to run the basic Alabama weather question.</summary>
```
 select ollama_chat_complete
( 'llama3'
, jsonb_build_array
  ( jsonb_build_object('role', 'system', 'content', 'you are a helpful assistant')
  , jsonb_build_object('role', 'user', 'content', 'what is the typical weather like in Alabama in June')
  )
, _options=> jsonb_build_object
  ( 'seed', 42
  , 'temperature', 0.6
  )
) as actual;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         actual
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {"done": true, "model": "llama3", "message": {"role": "assistant", "content": "June is a wonderful time to visit Alabama, with warm and sunny weather setting the stage for outdoor adventures!\n\nTypically, June is one of the hottest months in Alabama, with temperatures gradually warming up as summer approaches. Here's what you can expect:\n\n1. Temperatures: Daytime highs usually range from 84°F (29°C) to 88°F (31°C), while nighttime lows tend to be around 64°F (18°C) to 68°F (20°C).\n2. Humidity: June is a relatively humid month in Alabama, with an average relative humidity of 67%. This means you can expect some muggy days, especially near the Gulf Coast.\n3. Sunshine: Alabama gets plenty of sunshine during June, with an average of 9-10 hours of direct sunlight per day. This makes it perfect for outdoor activities like hiking, swimming, or simply enjoying a picnic in the park!\n4. Rainfall: June is generally a dry month in Alabama, with most areas receiving less than 3 inches (76 mm) of rainfall. However, occasional thunderstorms can still pop up, so it's always a good idea to pack an umbrella or rain jacket.\n\nRegional Variations:\n\n* The Gulf Coast, including Mobile and Pensacola, tends to be warmer and more humid than the rest of the state.\n* The Tennessee Valley, which includes Huntsville and Decatur, is generally cooler and drier than the southern parts of the state.\n* The mountainous regions, such as Lookout Mountain and the Appalachian foothills, can be slightly cooler and more temperate due to their higher elevations.\n\nOverall, June is a great time to enjoy Alabama's beautiful outdoors, with plenty of opportunities for swimming, fishing, hiking, and more. Just remember to pack sunscreen, a hat, and comfortable clothing to make the most of your visit!"}, "created_at": "2024-06-19T13:41:58.524074Z", "eval_count": 378, "done_reason": "stop", "eval_duration": 67161000000, "load_duration": 9117042, "total_duration": 67556060250, "prompt_eval_duration": 379790000}
(1 row)

Time: 67653.359 ms (01:07.653)
```  
</details>

For image processing it took 1 min and 9 seconds to complete the example done in the tests.

**Comment by jgpruitt** [comment]
@jonatas Oh wow! Good point. I guess I'm spoiled with my Apple M2 Pro. I didn't realize how slow it could be.

**Review by billy-the-fish — APPROVED** [review]

**Review by avthars — APPROVED** [review]
Hell yeah brother~!

**Pull request merged**
