### PR TITLE
Use tools with anthropic_generate (example type tool_use)

### PR DESCRIPTION
**Pull request by jonatas**
A minimal example of how to use tool_use.
<details>
  <summary>The original function gives me this error</summary>
  
  
```
 ERROR:  anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'tools: Input should be a valid list'}}
CONTEXT:  Traceback (most recent call last):
  PL/Python function "anthropic_generate", line 42, in <module>
    message = client.messages.create(model=_model, messages=_messages_1, max_tokens=_max_tokens, **args)
  PL/Python function "anthropic_generate", line 276, in wrapper
  PL/Python function "anthropic_generate", line 903, in create
  PL/Python function "anthropic_generate", line 1248, in post
  PL/Python function "anthropic_generate", line 930, in request
  PL/Python function "anthropic_generate", line 1028, in _request
 ```
</details>

 
Then, profiling with Claude, I just got this fix and I also added the final example porting same Name Entity Recognition.

TODO:

- [x] Wrap the code example into a useful function like `extract_entities`
image

- [x] Document the [JSON print_summary](https://github.com/anthropics/anthropic-cookbook/blob/main/tool_use/extracting_structured_json.ipynb)

### CODE REVIEW

**Review by jgpruitt — APPROVED** [review]
This is great. Thanks for the bug fixes.

**Review by jgpruitt — DISMISSED** [review]
@jonatas sorry for the mess. think you could rebase on the latest main?

**Comment by jonatas** [comment]
Rebased @jgpruitt!

**Comment by jgpruitt** [comment]
@jonatas  Awesome. You'll need to make the commit message conform to a "conventional commit format" https://github.com/conventional-changelog/commitlint

**Review by adolsalamanca — APPROVED** [review]

**Pull request merged**
